% Phase Diagrams
extraInputs = {'interpreter','latex','fontsize',15};

load('Fir.mat'); load('Sec.mat');
L = length(Xp1);
figure();
subplot(1,2,1)
plot(Xp1(220:L),Xp2(220:L),'LineWidth', 2.0, 'color', [.25,.25,.25]);
xlabel('$X$',extraInputs{:}); ylabel('$Y$',extraInputs{:});
xlim([-1,1.5]); ylim([-1,1]);
%title('Rossler');
subplot(1,2,2)
plot(Z1(220:L),Z2(220:L),'LineWidth', 2.0, 'color', [.25,.25,.25]);
xlabel('$\hat X$',extraInputs{:}); ylabel('$\hat Y$',extraInputs{:});
xlim([-1,1.5]); ylim([-1,1]);
%title('Phase Space Generated by Reservoir');